---
- name: Add Ondrej's PHP PPA repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    update_cache: true
- name: Install required PHP packages
  ansible.builtin.apt:
    name: "{{ php_packages }}"
    state: present
  notify: Show PHP version
- name: Symfony features
  ansible.builtin.import_tasks:
    file: symfony-cli.yml
  when: with_symfony | default(false)
